# Generated by Django 4.2 on 2024-07-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dorsal',
            old_name='camada',
            new_name='dorsal',
        ),
    ]
